config/routes.rb
Rails.application.routes.draw do
  root 'suggestions#index'

  get '/' => 'suggestions#index'

  post '/search_result' => 'suggestions#search_result'

  post '/suggestions/favorite' => 'suggestions#favorite', as: :add_favorite
  get '/suggestions/myfavs' => 'suggestions#favorites', as: :my_favorites

  delete 'suggestions/unfavorite' => 'suggestions#unfavorite', as: :unfavorite

  resources :sessions, :only => [:create]

  delete "/logout" => "sessions#destroy"
  get "/auth/:provider/callback" => "sessions#create"

end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :spotify_item


  # API data methods
  def self.new_from_api_data(business, spotify_item)
    return Suggestion.new do |suggestion|
      suggestion.restaurant = Restaurant.find_or_create_by_api_data(business)
      suggestion.spotify_item = SpotifyItem.find_or_create_by_api_data(spotify_item)
    end
  end

  def self.create_from_api_data(business, spotify_item)
    suggestion = self.new_from_api_data(business, spotify_item)
    return suggestion.save ? suggestion : nil
  end


  # API id methods
  def self.new_from_api_id(business_id, item_id)
    return Suggestion.new do |suggestion|
      suggestion.restaurant = Restaurant.find_or_create_by_api_id(business_id)
      suggestion.spotify_item = SpotifyItem.find_or_create_by_api_id(item_id)
    end
  end

  def self.create_from_api_id(business_id, item_id)
    suggestion = self.new_from_api_id(business_id, item_id)
    return suggestion.save ? suggestion : nil
  end

  # Find/Build methods
  def self.find_random(query, limit)
    restaurants = Restaurant.search(query, limit).shuffle
    spotify_items = SpotifyItem.search(query, limit).shuffle
    num_pairs = [restaurants.length, spotify_items.length].min

    # We'll just do single pairs for now, rather than cartesian product
    (0...num_pairs).map do |n|
      self.new_from_api_data(restaurants[n], spotify_items[n])
    end
  end
end

app/controllers/suggestions_controller.rb
require "#{Rails.root}/lib/charles/TunesTakeoutWrapper.rb"

class SuggestionsController < ApplicationController
before_action :require_login, only: [:favorites, :favorite, :unfavorites, :search_result]
  def index
    @top = Charles::TunesTakeoutWrapper.all_favorites

    if @top.nil?
      flash.now[:notice] = "Something went wrong, please try again"
    else
      @zip = @top.suggestions.map do |sugg_hash|
        [
        Music.create(sugg_hash["suggestion"]["music_type"], sugg_hash["suggestion"]["music_id"]),
        Food.find_in_api(sugg_hash["suggestion"]["food_id"]),
        sugg_hash["suggestion"]["id"]
        ]
      end
    end
  end

  def favorites
    @my_favorites = Charles::TunesTakeoutWrapper.get_my_favorite(current_user.uid)

    if @my_favorites.suggestions.nil?
      flash.now[:notice] = "Something went wrong, please try again"
    else
      @zip = @my_favorites.suggestions.map do |sugg_hash|
        [
        Music.create(sugg_hash['suggestion']["music_type"], sugg_hash['suggestion']["music_id"]),
        Food.find_in_api(sugg_hash['suggestion']["food_id"]),
        sugg_hash['suggestion']["id"]
        ]
      end
    end
  end

  def favorite
    @result = Charles::TunesTakeoutWrapper.add_favorite(params[:current_user_id], params[:suggestion_id])
    redirect_to my_favorites_path
  end

  def unfavorite
    @result = Charles::TunesTakeoutWrapper.delete_favorite(params[:current_user_id], params[:suggestion_id])
    redirect_to my_favorites_path
  end

  def search_result
    @all_suggestions = Charles::TunesTakeoutWrapper.find(params[:user_input])

    if @all_suggestions.suggestions.nil?
      flash.now[:notice] = "Something went wrong, please try again"
    else
      @zip = @all_suggestions.suggestions.map do |sugg_hash|
        [
        Music.create(sugg_hash["music_type"], sugg_hash["music_id"]),
        Food.find_in_api(sugg_hash["food_id"]),
        sugg_hash["id"]
        ]
      end
    end
  end
end

app/helpers/suggestions_helper.rb
module SuggestionsHelper
end

app/views/suggestions/_component.html.erb
<div class="suggestion">
  <div class="restaurant">
    <%= image_tag s.restaurant.image_url, alt: s.restaurant.name, class: "photo" %>
    <h3><%= link_to s.restaurant.name, s.restaurant.url %></h3>
  </div>
  <div class="spotify-item">
    <%= image_tag s.spotify_item.image_url, alt: s.spotify_item.name, class: "photo" %>
    <h3><%= link_to s.spotify_item.name, s.spotify_item.url %></h3>
  </div>
  <% if !s.persisted? -%>
    <%= form_tag suggestions_path, method: :post do %>
      <%= hidden_field_tag 'business_id', s.restaurant.business_id %>
      <%= hidden_field_tag 'item_id', s.spotify_item.item_id %>
      <%= submit_tag "Save", class: "btn-save" %>
    <% end -%>
  <% end -%>
</div>

app/views/suggestions/_display.html.erb
<% if @zip %>
<% @zip.map do |pair|%>
      <table class="table">
        <tr>
          <td class="music">
          <%= link_to pair[0].open_spotify_url, target: :_blank do %>
          <%= image_tag pair[0].image, size: '100X100', alt: "Profile Photo", class: "spotifypic" %>
          <div class='spotifytitle'>

          <h3><%= pair[0].name %></h3>
          <strong>Type : </strong><%= pair[0].type.capitalize %>
          <% end %>
          </div>
          <br>

          <br>

          <br>
          <iframe src="https://embed.spotify.com/?uri=<%= pair[0].uri %>&theme=white" frameborder="0" allowtransparency="true"></iframe>
          </td>

          <%if current_user%>
          <td class="fava">
          <%= form_tag add_favorite_path, method: :post do %>
          <%=hidden_field_tag :current_user_id, current_user.uid%>
          <%=hidden_field_tag :suggestion_id, pair[2]%>
          <%=submit_tag 'Favorite!', class: "btn btn-primary"%>
          <%end%>
          </td>
          <%end%>


          <td class="food">
            <div class="yelpheader">
              <%= link_to pair[1].open_yelp_url, target: :_blank do %>
              <%= image_tag pair[1].the_image_url, alt: pair[1].the_image_url, class: "yelp_pic" %>
              <h3 class="yelpheaderti"><%= pair[1].name %></h3>
              <% end %>
              <% unless  pair[1].display_phone.nil? %>
              <%= link_to "tel:#{pair[1].display_phone}" do%>
              <span class="glyphicon glyphicon-phone-alt">&nbsp;</span>  <%= pair[1].display_phone[3..-1]  %>
              <% end %>

              <% end %>
              <br>
              <br>

              <%  pair[1].location.map do |loc| %>
                <%= loc %>
                <br>
              <%end %>
            </div>
          <br>
          <div class="yelprates">
            <strong>Rating : </strong><%=  pair[1].rating%>
            <%= image_tag pair[1].rating_img_url_large, alt: pair[1].rating_img_url_large, class: "ratingpic" %>
            <br>
            <strong>Total Reviews: </strong><%=  pair[1].review_count%>
          </div>

          <br>
          <strong>Categories : </strong><% pair[1].categories.map do |cat| %>
            <%= cat[0] + ". " %>
          <%end %>
          </td>

        </tr>
      </table>

<%end%>
<%end%>

app/views/suggestions/_suggestion.html.erb
<% if @zip %>
<% @zip.map do |pair|%>
      <table class="table">
        <tr>
          <td class="music">
          <%= link_to pair[0].open_spotify_url, target: :_blank do %>
          <%= image_tag pair[0].image, size: '100X100', alt: "Profile Photo", class: "spotifypic" %>
          <div class='spotifytitle'>

          <h3><%= pair[0].name %></h3>
          <strong>Type : </strong><%= pair[0].type.capitalize %>
          <% end %>
          </div>
          <br>

          <br>

          <br>
          <iframe src="https://embed.spotify.com/?uri=<%= pair[0].uri %>&theme=white" frameborder="0" allowtransparency="true"></iframe>
          <%= button_to "Open in Spotify", pair[0].open_spotify_url, method: :get, class: "btn btn-success"  %>

          </td>

          <%if current_user%>
          <td class="fava">
          <%= form_tag add_favorite_path, method: :post do %>
          <%=hidden_field_tag :current_user_id, current_user.uid%>
          <%=hidden_field_tag :suggestion_id, pair[2]%>
          <%=submit_tag 'Favorite!', class: "btn btn-primary"%>
          <%end%>
          <br>

          <%= form_tag unfavorite_path, method: :delete do %>
          <%=hidden_field_tag :current_user_id, current_user.uid%>
          <%=hidden_field_tag :suggestion_id, pair[2]%>
          <%=submit_tag 'Unfavorite!', class: "btn btn-primary"%>
          <%end%>
          </td>
          <%end%>


          <td class="food">
            <div class="yelpheader">
              <%= link_to pair[1].open_yelp_url, target: :_blank do %>
              <%= image_tag pair[1].the_image_url, alt: pair[1].the_image_url, class: "yelp_pic" %>
              <h3 class="yelpheaderti"><%= pair[1].name %></h3>
              <% end %>
              <% unless  pair[1].display_phone.nil? %>
              <%= link_to "tel:#{pair[1].display_phone}" do%>
              <span class="glyphicon glyphicon-phone-alt">&nbsp;</span>  <%= pair[1].display_phone[3..-1]  %>
              <% end %>

              <% end %>
              <br>
              <br>

              <%  pair[1].location.map do |loc| %>
                <%= loc %>
                <br>
              <%end %>

            </div>
          <br>
          <div class="yelprates">
            <strong>Rating : </strong><%=  pair[1].rating%>
            <%= image_tag pair[1].rating_img_url_large, alt: pair[1].rating_img_url_large, class: "ratingpic" %>
            <br>
            <strong>Total Reviews: </strong><%=  pair[1].review_count%>
          </div>

          <br>
          <strong>Categories : </strong><% pair[1].categories.map do |cat| %>
            <%= cat[0] + ". " %>
          <%end %>
          <%= button_to "Open in Yelp", pair[1].open_yelp_url, method: :get, class: "btn btn-danger"  %>
          </td>

        </tr>
      </table>

  <%end%>
<%end%>

app/views/suggestions/favorite.html.erb
<%= @result %>

app/views/suggestions/favorites.html.erb
<h1>Favorites for <%=current_user.uid%>!!</h1>

<%= render partial: "suggestion"%>

app/views/suggestions/index.html.erb
<%= render partial: "suggestion"%>

app/views/suggestions/search_result.html.erb
<%= render partial: "suggestion"%>

app/views/suggestions/show.html.erb
<%= render partial: "component", locals: { s: @suggestion } %>

app/views/suggestions/unfavorite.html.erb
<h1>Suggestions#unfavorite</h1>
<p>Find me in app/views/suggestions/unfavorite.html.erb</p>